services:
  - type: web
    name: ecomerce-clothes
    env: docker
    dockerfilePath: ./ecomerce.clothes/Dockerfile
    dockerContext: .
    plan: free
    region: oregon
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: PORT
        value: 8080
    healthCheckPath: /actuator/health
